project_name: xxx项目名称

env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: Rainx

host: https://www.iamwawa.cn

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: True